Обратная сторона реальности
htmlacademy-react/1353597-six-cities-7 pull request #5
Opened 2021-06-12 08:58 UTC by Sellywer

2021-06-12 18:08 UTC, dtsaryov requested changes
Очень много всяких мелких проблем, связанных с именованием.

Убери ненужные суффиксы / префиксы, проверь корректность использования множественного числа.

Проверь, что имена модулей и компонентов совпадают и т.д

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-card.jsx
> +function FavoriteCard({offer}) {
Опять проблемы со множественным числом в именах

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-item.jsx
> +import FavoriteCard from './favorites-card';
имя компонента и файла не совпадают

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-item.jsx
> +  );
В одну строку, пожалуйста

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-item.jsx
> +        ))}
В одну строку

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-list.jsx
> +  const favoritesCities = [...uniqueCities.values()];
Это все можно сделать одной строкой.

Не получится - пиши

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/pages/page-favorites/favorites-list.jsx
> +function FavoritesList(props) {
Favorites, но FavoriteList - везде поправь

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/reviews/reviews-item.jsx
> +  });
Вынеси во внешнюю функцию на уровне модуля

2021-06-12 18:08 UTC, dtsaryov commented on project/src/components/place-card/place-card.jsx
> +                stroke: `${isFavorite ? '#4481c3' : '#979797'}`,
Цвета в перечисление, пожалуйста

2021-06-15 17:29 UTC, Sellywer commented on project/src/components/app/app.jsx
> +import PageRoom from '../pages/page-room/page-room';
room - потому что по тз в роутере так называется)))) Room (/offer/:id). Но да, это все таки предложения

2021-06-15 17:29 UTC, Sellywer commented on project/src/utils.js
> +export const calcRatingInPercent = (rating) => `${rating / 5 * 100}%`;
она у меня в 3х местах используется

2021-06-15 17:31 UTC, Sellywer commented on project/src/components/app/app.jsx
> +import PageLogin from '../pages/page-login/page-login';
лучше page вовсе убрать, или заменить на чтото другое? ну из всего все таки думаю либо page, либо совсем без ничего, но тогда вопрос: нужно ли главные страницы объединять в папку pages или вовсе разделить?

2021-06-17 19:01 UTC, dtsaryov approved these changes

2021-06-17 19:01 UTC, merged